zuul:
  routes:
    obra:
      path: /obra/**
      url: https://dan-usuarios-staging.herokuapp.com/api/obra
    cliente:
      path: /cliente/**
      url: https://dan-usuarios-staging.herokuapp.com/api/cliente
    empleado:
      path: /empleado/**
      url: https://dan-usuarios-staging.herokuapp.com/api/empleado

eureka:
  client:
    enabled: false